### ISSUE TITLE
Is there a plan to have localtunnel as a .NET global tool?

### ISSUE THREAD

**Issue by jmoralesv** [angelobreuer/localtunnel-client#1]
Hi,
I was looking for an open source alternative to ngrok and found your project, I was wondering if there are any plans on supporting localtunnel as a .NET global tool, so that we can install it through the dotnet command line. 

This is from the Microsoft docs: https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create

I can also help with that, I think it would be a great addition to this project.

Best regards,
Jorge

**Comment by angelobreuer** [comment]
Great idea! I published the package on nuget.org, so you can install it with `dotnet tool install localtunnel --global`.

Note that the first published version is 1.1.0 (instead of 1.0.0).

I will also update README accordingly.

**Comment by jmoralesv** [comment]
Hi @angelobreuer 
It works as expected, I've just installed it as a global tool, I had to use another subdomain for my tests as the previous one looks like it is still reserved.

Thank you very much!

**Comment by angelobreuer** [comment]
> Is there a plan to have as a Nuget too?

@azhe403 I had some time to try this out and I noticed that my assumption was right and we are not able to "simply" use the current NuGet package. I will do some structural changes to make it possible to use the localtunnel client as a class library.
