### ISSUE TITLE
Are there any plans to implement also a serverside component?

### ISSUE THREAD

**Issue by savage8811** [angelobreuer/localtunnel-client#11]
I really like this project and I wonder if there are also plans for a server side component (localtunnel-server) in .NET?

**Comment by angelobreuer** [comment]
Hello @savage8811, currently this is a client for localtunnel.me, which is a server hosted publicy by someone. The source code for the server (in JavaScript) lies on https://github.com/localtunnel/server (which can also be built to run on an own server, you can use a CLI flag to use your own server endpoint for the .NET client). 

Currently, there are no plans for a server side implementation, but I think it would not be too hard to implement this in .NET.

**Comment by savage8811** [comment]
Thank you for your reply. PS: Too hard for me ;-)
