### ISSUE TITLE
Localtunnel Client as a class library

### ISSUE THREAD

**Issue by angelobreuer** [angelobreuer/localtunnel-client#4]
(As of request: https://github.com/angelobreuer/localtunnel-client/issues/1#issuecomment-838350604)

Currently, the localtunnel client was only intended to be used by using the command-line interface. Making the localtunnel client available as a NuGet package requires some structural changes. 

- First, the CLI code must be ported to another assembly, which represents the new NuGet package containing the binaries for the dotnet-tool.
- Second, the current localtunnel assembly loses some dependencies (System.CommandLine and Microsoft.Extensions.Logging.Console) which will be added to the CLI assembly. Additionally, a new dependency to Microsoft.Extensions.Logging.Abstractions will be introduced to stay compatible with the current logging implementation.

This is a breaking change for those who use the localtunnel client as a dotnet tool.

**Comment by angelobreuer** [comment]
Fixed via #5

**Comment by azhe403** [comment]
Thanks for this change. I'm really appreciate!
